site_name: Alton Lavin D'Souza
site_url: https://Alton1998.github.io/alton.github.io/

# Markdown Extensions
markdown_extensions: 
  - pymdownx.arithmatex:
      generic: true
  - fenced_code
  - codehilite
  - footnotes

# MathJax Integration
extra_javascript: 
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

# Plugins
plugins:
  - blog:
      blog_dir: blog/
      archive: true
      feed: true
      categories: true
  - search
  - rss:
      match_path: blog/posts/.*

# Theme Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes

# Navigation
nav:
  - About: index.md
  - Work Experience:
      - Oracle: work_experience/oracle.md
  - Projects:
      - Arrhythmia Detection: projects/arrhythmia.md
      - Corona Virus Detection in Chest X-Rays: projects/chest_x_rays.md
      - Tensor Processing Unit: projects/tpu.md
  - Blog: blog/index.md
