site_name: Alton Lavin D'souza
site_url: https://Alton1998.github.io/alton.github.io/
python:
   version: 3 # for unicode
   setup_py_install: true

#the third-party extenison mdx_math.py comes with a setup.py script
# Thank you Dmitry Shachnev (https://github.com/mitya57/python-markdown-math) 
markdown_extensions: 
    - mdx_math:
        enable_dollar_delimiter: True #for use of inline $..$
    - fenced_code
    - codehilite
    - footnotes

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']
plugins:
  - blog:
      blog_dir: blog/
      categories_pagination: true
  - search
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes
nav:
  - About: index.md
  - Work Experience:
    - Oracle: work_experience/oracle.md
  - Projects:
    - Arrhythmia Detection: projects/arrhythmia.md
    - Corona Virus Detection in Chest X-Rays: projects/chest_x_rays.md
    - Tensor Processing Unit: projects/tpu.md
  - Blog: blog/index.md
    # - Detect AI Generated Texts:
    # - Creating A 
  # - Learnings:
  #   - Python:
  #   - Java:
  #   - Deep Learning:
  #   - NLP:
  #   - Image Processing: